
locale: en

replace-only-fish: true
only-for-contest: false


presets:
  junk:
    display-name: "&7&lJUNK &7"
    conditions:
      chance: 1
    shop:
      price: 0
  common:
    prefix: "&r&lCOMMON &r"
    conditions:
      chance: 100
    item:
      id: "minecraft:cod"
  rare:
    display-name: "&b&lRARE &b"
    conditions:
      chance: 22
    shop:
      additional-price: 3.0
  epic:
    display-name: "&d&lEPIC &d"
    conditions:
      chance: 6.5
    shop:
      additional-price: 4.0
  legendary:
    display-name: "&2&lLEGENDARY &2"
    conditions:
      chance: 0.5
    shop:
      additional-price: 5.0
    effects:
      catch:
        firework: true

fish-types:
  shrimp:
    preset: common
    name: "Shrimp"
    length: 3..8
  anchovy:
    preset: common
    name: "Anchovy"
    length: 7..13
  croaker:
    preset: common
    name: "Croaker"
    length: 12..15
  crab:
    preset: common
    name: "Crab"
    length: 10..15
  mackerel:
    preset: common
    name: "Mackerel"
    length: 15..30
  herring:
    preset: common
    name: "Herring"
    length: 20..30

  junk:
    pie:
      preset: junk
      name: "Pie"
      length: 3.14..3.14
      item:
        id: pumpkin_pie
    Magikarp:
      display-name: "Magikarp"
      length-min: 25
      length-max: 35
      icon:
        id: "minecraft:cod"
        lore:
        - "&7Magikarp used Splash!"
      skip-item-format: false
    Breadfish:
      display-name: "Breadfish"
      length-min: 10
      length-max: 30
      icon:
        id: "minecraft:bread"
        lore:
        - "&7Tell me have you seen"
        - "&7the marvellous breadfish"
      skip-item-format: false
    WoodenAxe:
      display-name: "Admin's Wooden Axe"
      length-min: 16
      length-max: 16
      icon:
        id: "minecraft:wooden_axe"
        lore:
        - "&7//cut"
      skip-item-format: false
    FishingRod:
      display-name: "Fishing Rod That Someone Dropped Hitting 'Q' By Mistake"
      length-min: 16
      length-max: 16
      icon:
        id: "minecraft:fishing_rod"
        durability: 30
      skip-item-format: true
    SpongeBob:
      display-name: "Nice Cook Of The Krusty Krab"
      length-min: 16
      length-max: 16
      icon:
        id: "minecraft:sponge"
      skip-item-format: true
  rare:
    Jellyfish:
      display-name: "Jellyfish"
      length-min: 20
      length-max: 40
      icon:
        id: "minecraft:cod"
      commands:
      - "minecraft:effect give @p minecraft:poison 3 1"
      - "tellraw @p [\"\",{\"text\":\"[MoreFish]\",\"color\":\"aqua\"},{\"text\":\" The jellyfish made you feel very bad!\",\"color\":\"none\"}]"
    Squid:
      display-name: "Squid"
      length-min: 30
      length-max: 50
      icon:
        id: "minecraft:ink_sac"
      commands:
      - "minecraft:effect give @p minecraft:blindness 5 1"
      - "tellraw @p [\"\",{\"text\":\"[MoreFish]\",\"color\":\"aqua\"},{\"text\":\" The squid gifted you some darkness!\",\"color\":\"none\"}]"
    Flatfish:
      display-name: "Flatfish"
      length-min: 40
      length-max: 75
      icon:
        id: "minecraft:cod"
    SeaBream:
      display-name: "Sea Bream"
      length-min: 50
      length-max: 70
      icon:
        id: "minecraft:cod"
    SeaBass:
      display-name: "Sea Bass"
      length-min: 60
      length-max: 100
      icon:
        id: "minecraft:cod"
  epic:
    Clownfish:
      display-name: "Clownfish"
      length-min: 10
      length-max: 18
      icon:
        id: "minecraft:tropical_fish"
    Pufferfish:
      display-name: "Pufferfish"
      length-min: 20
      length-max: 30
      icon:
        id: "minecraft:pufferfish"
    SeaTurtle:
      display-name: "Sea Turtle"
      length-min: 90
      length-max: 130
      icon:
        id: "minecraft:cod"
    Salmon:
      display-name: "Salmon"
      length-min: 100
      length-max: 130
      icon:
        id: "minecraft:salmon"
    BlackDrum:
      display-name: "Black Drum"
      length-min: 100
      length-max: 180
      icon:
        id: "minecraft:cod"
    Tuna:
      display-name: "Tuna"
      length-min: 130
      length-max: 180
      icon:
        id: "minecraft:cod"
  legendary:
    BlueShark:
      display-name: "Blue Shark"
      length-min: 160
      length-max: 240
      icon:
        id: "minecraft:cod"
        lore:
        - "&7&oThe Toughest Fish"
        - "&7Get &9Strength I (2:00)&7 when you eat it."
      food-effects:
        commands:
        - "minecraft:effect give @p minecraft:strength 120 1"
    PygmyWhale:
      display-name: "Pygmy Whale"
      length-min: 600
      length-max: 650
      icon:
        id: "minecraft:cod"
        lore:
        - "&7&oThe Biggest Fish"
        - "&7Get &9full health and hunger&7"
        - "when you eat it."
      food-effects:
        points: 20
        saturation: 14.4
        commands:
        - "minecraft:effect give @p minecraft:regeneration 2 127"
